class_path: superhuge.models.commons.m_interface.MInterface
init_args:
  model_class: superhuge.models.rebok_deformer.rebok_torch_deformer.rebok_deformer
  model_args:
    window_length: 10
    fs: 128
    num_kernels: 32
    temporal_kernel_size: 13
    mha_depth: 4
    mha_num_heads: 8
    mha_dim_heads: 160
    time_dim: 1280
    mha_embed_dim: 1280
    ff_hidden_dim: 128
    num_electrodes: 70
    dp_rate: .5
    # preconv_callable: superhuge.models.rebok_deformer.deformer.preconv
    # transformer_callable: superhuge.models.rebok_deformer.rebok_torch_deformer.rebok_transformer
