---
class_path: superhuge.models.interface.model_interface.MInterface
init_args:
  model_class: superhuge.torch_models.simple_cnn.SimpleCNN
  model_args:
    temporal_kernel_size: 17
    num_kernels: 5
