---
class_path: superhuge.model.interface.MInterface
init_args:
  model_args:
    extractor_args:
      kernel_sizes: [3, 11, 17, 5, 13]
      num_kernels: [64, 64, 64, 32, 32]
      num_layers: 5
    nb_blocks: 1
    output_context_args:
      kernel_size: 15
      num_kernel: 32
  model_class: superhuge.model.pure_cnn.VLAAI
