---
class_path: superhuge.models.commons.m_interface.MInterface
init_args:
  model_args:
    extractor_args:
      kernel_sizes: [17]
      num_kernels: [64]
      num_layers: 5
    input_channels: 70
    nb_blocks: 4
    output_context_args:
      kernel_size: 9
      num_kernel: 64
    window_length: 10
    fs: 128
  model_class: superhuge.models.vlaai.vlaai.vlaai
