---
data:
  class_path: superhuge.datasets.commons.data_interface.DInterface
  init_args:
    dataloader_args:
      batch_size: 4
      num_workers: 2
      persistent_workers: true
      prefetch_factor: 8
      pin_memory: true
      drop_last: false
    dataset_args:
      fs: 128
      metadata_fields:
        - dataset_id
        - subject_id
        - trial_id
        - signal_length
        - num_channel
        - fs
        - channel_infos
      n_folds: 5
      overlap: 1
      root_path: /data/nvme/ssd2/zhangyuanming/EEG/derivatives/SuperHuge
      transform: null
      window_length: 10
      meta_filter_func:
        class_path: superhuge.datasets.metadata_processing.filters.composer.MetaDataFilterComposer
        init_args:
          - class_path: superhuge.datasets.metadata_processing.filters.MetadataValueSelector
            init_args:
              attribute_name: dataset_id
              attribute_value:
                - 1
                # - 3
                # - 5
          - class_path: superhuge.datasets.metadata_processing.filters.classify_filter.binary_leftright_filter
lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    cooldown: 5
    eps: 1.e-8
    factor: 0.5
    min_lr: 1.e-8
    mode: min
    monitor: val/loss
    patience: 5
    threshold: 0.0001
    threshold_mode: rel
optimizer:
  class_path: Adam
  init_args:
    betas: [0.9, 0.999]
    eps: 1.e-8
    lr: 1.e-3
    weight_decay: 1.e-4
seed_everything: 42
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  barebones: false
  benchmark: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        min_delta: 0.01
        mode: min
        monitor: val/loss
        patience: 10
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        mode: min
        monitor: val/loss
        save_last: true
        save_top_k: 2
        save_weights_only: true
    - class_path: superhuge.utils.fancy_progress_bar.FancyProgressBar
      init_args:
        refresh_rate: 5
  check_val_every_n_epoch: 1
  default_root_dir: null
  detect_anomaly: false
  deterministic: true
  devices: auto
  enable_checkpointing: null
  enable_model_summary: null
  enable_progress_bar: null
  fast_dev_run: false
  gradient_clip_algorithm: null
  gradient_clip_val: null
  inference_mode: true
  limit_predict_batches: null
  limit_test_batches: null
  limit_train_batches: null
  limit_val_batches: null
  log_every_n_steps: null
  logger: null
  max_epochs: 50
  max_steps: -1
  max_time: null
  min_epochs: 20
  min_steps: null
  num_nodes: 1
  num_sanity_val_steps: null
  overfit_batches: 0
  plugins: null
  precision: null
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  strategy: auto
  sync_batchnorm: false
  use_distributed_sampler: true
  val_check_interval: 0.5
