class_path: lightning.pytorch.cli.ReduceLROnPlateau
init_args:
  cooldown: 3
  eps: 1.e-8
  factor: 0.5
  min_lr: 1.e-8
  mode: max
  monitor: val/acc_epoch
  patience: 5
  threshold: 1.e-4
  threshold_mode: rel
