class_path: superhuge.models.commons.model_interface.ClassifierInterface
init_args:
  model_class: superhuge.models.commons.rebok_deformer.deformer
  model_args:
    window_length: 10
    fs: 128,
    num_kernels: 32
    temporal_kernel_size: 17
    mha_depth: 4
    mha_num_heads: 32
    mha_dim_heads: 128
    ff_hidden_dim: 256
    num_electrodes: 32
    dp_rate: .5
    preconv_callable: superhuge.models.commons.rebok_deformer.preconv
    transformer_callable: superhuge.models.commons.rebok_deformer.transformer
  loss:
    class_path: torch.nn.modules.loss.CrossEntropyLoss
    init_args:
      weight: null
      size_average: null
      ignore_index: -100
      reduce: null
      reduction: "mean"
  loss_hparams: null

