init_args:
  optimizer_class: torch.optim.AdamW
  optimizer_args:
    lr: 1.e-3
    weight_decay: 0
    fused: true
  lr_scheduler_class: torch.optim.lr_scheduler.ReduceLROnPlateau
  lr_scheduler_args:
    mode: min
    factor: 0.5
    patience: 10
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 5
    min_lr: 1.e-9
    eps: 1.e-08
