directional_focus_decoding:
  type: classification
  general:
    data:
      init_args:
        dataset_class: superhuge.data.datasets.EegClassifyBaseDataset
        metadata_fields:
          [
            "dataset_id",
            "subject_id",
            "trial_id",
            "signal_length",
            "num_channel",
            "fs",
            "label",
            "channel_infos",
          ]
        n_folds: 5
    model:
      class_path: superhuge.model.interface.ChannelMapping1DClassifyInterface
      # class_path: superhuge.model.interface.ChannelMixing1DClassifyInterface
      init_args:
        hidden_dim: 5
        # num_mix_out_channels: 64
        loss:
          class_path: superhuge.model.loss.CrossEntropyLoss
  tasks:
    binary_leftright:
      enable: 1
      data:
        init_args:
          meta_filter_func_args:
            - binary_leftright
      model:
        init_args:
          num_class: 2
    binary_frontrear:
      enable: 0
      data:
        init_args:
          meta_filter_func_args:
            - binary_frontrear
      model:
        init_args:
          num_class: 2
    four-class:
      enable: 0
      data:
        init_args:
          meta_filter_func_args:
            - four-class
      model:
        init_args:
          num_class: 4
    eight-class:
      enable: 0
      data:
        init_args:
          meta_filter_func_args:
            - eight-class
      model:
        init_args:
          num_class: 8

  cross_validation:
    leave_one_trial_out:
      enable: 1
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.loto
          n_folds: 5
    leave_one_subject_out:
      enable: 0
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.loso
          n_folds: 16
    leave_one_dataset_out:
      enable: 0
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.lodo

speech_reconstruction:
  type: regression
  general:
    data:
      init_args:
        dataset_class: superhuge.data.datasets.EegRegressionBaseDataset
        n_folds: 6
        metadata_fields:
          [
            "dataset_id",
            "subject_id",
            "trial_id",
            "signal_length",
            "num_channel",
            "fs",
            "env",
            "channel_infos",
          ]

    model:
      class_path: superhuge.model.interface.ChannelMapping1DRegressionInterface
      init_args:
        num_audio_features: 1
        loss:
          class_path: superhuge.model.loss.MSELoss
  tasks:
    envelope_reconstruction:
      enable: 0
      data:
        init_args:
          meta_filter_func_args:
            - env

  cross_validation:
    leave_one_trial_out:
      enable: 1
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.loto
    leave_one_subject_out:
      enable: 0
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.loso
    leave_one_dataset_out:
      enable: 0
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.lodo
