<<<<<<< HEAD
directional_focus_decoding:
  type: classification
  general:
    data:
      init_args:
        dataset_class: src.datasets.eeg_classify_base_dataset.EegClassifyBaseDataset
        dataset_args:
          metadata_fields:
            [
              "dataset_id",
              "subject_id",
              "trial_id",
              "signal_length",
              "num_channel",
              "fs",
              "label",
            ]
          n_folds: 5
  tasks:
    binary_leftright:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_filter_func_args:
              - binary_leftright
      model:
        init_args:
          model_args:
            num_class: 2
    binary_frontrear:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_filter_func_args:
              - binary_frontrear
      model:
        init_args:
          model_args:
            num_class: 2
    four-class:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_filter_func_args:
              - four-class
      model:
        init_args:
          model_args:
            num_class: 4
    eight-class:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_filter_func_args:
              - eight-class
      model:
        init_args:
          model_args:
            num_class: 8

  cross_validation:
    leave_one_trial_out:
      enable: 1
      data:
        init_args:
          dataset_args:
            meta_group_func: src.datasets.metadata_processing.loto
    leave_one_subject_out:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_group_func: src.datasets.metadata_processing.loso
    leave_one_dataset_out:
      enable: 0
      data:
        init_args:
          dataset_args:
            meta_group_func: src.datasets.metadata_processing.lodo

speech_reconstruction:
=======
dnn_envelope_reconstruction:
>>>>>>> python-package-working
  type: regression
  general:
    data:
      init_args:
        dataset_class: superhuge.data.datasets.EegRegressionBaseDataset
        n_folds: 4
        metadata_fields: ["env"]
        meta_filter_func_args:
          - env
    model:
      class_path: superhuge.model.interface.RegressionInterface
      init_args:
        num_audio_features:
          env: 1
        model_common_args:
          num_channels: 64

  tasks:
    pcc_diff:
      enable: 1
      model:
        init_args:
          loss:
            class_path: superhuge.model.loss.ContrastivePearsonLoss

    pcc:
      enable: 1
      model:
        init_args:
          loss:
            class_path: superhuge.model.loss.PearsonLoss

  cross_validation:
    leave_one_trial_out:
      enable: 1
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.loto
    leave_one_subject_out:
      enable: 0
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.loso
    leave_one_dataset_out:
      enable: 0
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.lodo

linear_envelope_reconstruction:
  type: regression
  general:
    data:
      init_args:
        dataset_class: superhuge.data.datasets.EegRegressionBaseDataset
        n_folds: 12
        metadata_fields:
          - env
        meta_filter_func_args:
          - env
    model:
      class_path: superhuge.model.interface.LinearRegressionInterface
      init_args:
        model_common_args:
          num_channels: 64

  tasks:
    pcc:
      enable: 0
      model:
        init_args:
          num_audio_features:
            env: 1
          loss:
            class_path: superhuge.model.loss.ContrastivePearsonLoss

  cross_validation:
    leave_one_trial_out:
      enable: 0
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.loto
    leave_one_subject_out:
      enable: 1
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.loso
    leave_one_dataset_out:
      enable: 0
      data:
        init_args:
          meta_group_func: superhuge.data.metadata_processing.lodo
